# dev profile
---
server:
  port: 8080
logging:
  file: /target/classes/myapp.log
  file.append: true
  level:
    org.springframework: info
spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: create-drop
  data:
    mongodb:
      database: CourseDb
      auto-index-creation: true
      authentication-database: admin
      host: localhost
      port: 27017
      username: admin
      password: pass